Write a Python program to convert categorical data (e.g., Yes/No) into numerical values (1/0) and display the updated dataset.

In [4]:
import numpy as np
import pandas as pd

In [21]:
df = pd.DataFrame(columns=['StudentID', 'Study_Hours', 'Marks', 'Good'])

df['StudentID'] = ['S1','S2','S3','S4','S5']
df['Study_Hours'] = [2, 3, None, 5, 6]
df['Marks'] = [35, 40, 45, None, 70]
df['Good'] = ["Yes", "No", "Yes", "Yes", "No"]

catMap = {
    'Yes' : 1,
    'No' : 0
}
df['Good'] = df['Good'].map(catMap)

df

  StudentID  Study_Hours  Marks  Good
0        S1          2.0   35.0     1
1        S2          3.0   40.0     0
2        S3          NaN   45.0     1
3        S4          5.0    NaN     1
4        S5          6.0   70.0     0

In [20]:
df['StudentID'][::-1]

4        S5
3        S4
2        S3
1    Pranav
0        S1
Name: StudentID, dtype: str

In [18]:
df.loc[df['StudentID'] == 'S2', 'StudentID'] = 'Pranav'
df

  StudentID  Study_Hours  Marks  Good
0        S1          2.0   35.0     1
1    Pranav          3.0   40.0     0
2        S3          NaN   45.0     1
3        S4          5.0    NaN     1
4        S5          6.0   70.0     0

In [28]:
df.isnull()
df

  StudentID  Study_Hours  Marks  Good
0        S1          2.0   35.0     1
1        S2          3.0   40.0     0
2        S3          NaN   45.0     1
3        S4          5.0    NaN     1
4        S5          6.0   70.0     0